name: easy_nginx
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.1
  pedantic: ^1.10.0
dependencies:
  args: ^2.2.0
  tuple: ^2.0.0
